#!/usr/bin/env python3
import hashlib
import os
import shutil
import struct
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
ASSETS = ROOT / "BlurFaces" / "assets"
INPUTS = {
    "dex/core.dex": ROOT / "build" / "dex" / "core.dex",
    "dex/mediapipe-runtime.dex": ROOT / "build" / "dex" / "mesh-runtime.dex",
    "jni/arm64-v8a/libmediapipe_tasks_vision_jni.so": ROOT / "build" / "mesh-runtime" / "libmediapipe_tasks_vision_jni.so",
}


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def validate(name, path):
    data = path.read_bytes()[:20]
    if name.endswith(".dex") and not data.startswith(b"dex\n035\0"):
        raise ValueError(f"not a Dalvik 035 DEX: {path}")
    if name.endswith(".so"):
        if data[:4] != b"\x7fELF" or data[4] != 2 or data[5] != 1:
            raise ValueError(f"not a 64-bit little-endian ELF: {path}")
        machine = struct.unpack("<H", data[18:20])[0]
        if machine != 183:
            raise ValueError(f"ELF is not AArch64: {path}")


stale_model_dir = ASSETS / "model"
if stale_model_dir.exists():
    shutil.rmtree(stale_model_dir)


for name, source in INPUTS.items():
    if not source.is_file() or source.stat().st_size == 0:
        raise FileNotFoundError(f"mandatory build input missing: {source}")
    validate(name, source)
    target = ASSETS / name
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, target)
    validate(name, target)
    if target.read_bytes() != source.read_bytes():
        raise ValueError(f"staged payload differs: {name}")

hashes = {name: sha256(ASSETS / name) for name in sorted(INPUTS)}
hash_file = ROOT / "BlurFaces" / "asset_hashes.py"
with hash_file.open("w", encoding="ascii") as output:
    output.write("# Generated by build.py; ./build.sh refreshes these fixed runtime expectations.\n")
    output.write("ASSET_HASHES = {\n")
    for name, digest in hashes.items():
        output.write(f'    "{name}": "{digest}",\n')
    output.write("}\n")

for name, digest in hashes.items():
    print(f"{digest}  BlurFaces/assets/{name}")
