plugins {
    id 'com.android.library' version '8.2.2'
}

android {
    namespace 'com.makey.blurfaces'
    compileSdk 35
    defaultConfig { minSdk 26 }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions {
        unitTests.returnDefaultValues = true
    }
}

repositories { google(); mavenCentral(); maven { url 'https://maven.aliucord.com/snapshots' } }

tasks.register("aarToCoreDex") {
    dependsOn "assembleRelease"
    doLast {
        def ownAar = file("$buildDir/outputs/aar/${project.name}-release.aar")
        def inputDir = file("$buildDir/dex-input")
        delete inputDir; mkdir inputDir
        copy { from zipTree(ownAar); include 'classes.jar'; into inputDir; rename { 'plugin-classes.jar' } }
        def output = file("$buildDir/dex/core")
        delete output; mkdir output
        exec { commandLine "${android.sdkDirectory}/build-tools/36.0.0/d8", file("$inputDir/plugin-classes.jar"), "--output", output }
    }
}

tasks.register("stageDex") {
    dependsOn "aarToCoreDex"
    doLast {
        def output = file("$buildDir/dex")
        copy { from "$output/core/classes.dex"; into output; rename { 'core.dex' } }
    }
}

tasks.register("buildDex") { dependsOn "stageDex" }

dependencies {
    compileOnly files('libs/exteragram.jar')
    compileOnly 'com.aliucord:Aliuhook:1.1.3'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.aliucord:Aliuhook:1.1.3'
    testImplementation files('libs/exteragram.jar')
}
