# Generated by build.py; ./build.sh refreshes these fixed runtime expectations.
ASSET_HASHES = {
    "dex/core.dex": "7f94bbb778defc6ef6da7c50cf6e4659b0f04223c61dd2d9cfbff449bda07769",
    "jni/arm64-v8a/libblur_faces.so": "e26989e89f5eac7e8b61295fd26da12b0a3885ec70c6ec9f5fedcafca6bf0aa1",
    "model/head_det.bin": "7aaafe2c2921aad54363a3a859fa9f67c0f2b1589c59e1e8c38208d5a41499d0",
    "model/head_det.param": "294ca3b93ff08f75ef68186472adb0c72b933c03500ca4ac59cabf429a840e2d",
}
