# Generated by build.py; ./build.sh refreshes these fixed runtime expectations.
ASSET_HASHES = {
    "dex/core.dex": "9f156463651e10755a8749c204cbd8f8e1b5b86af7d084cf270b4cafea5ba1cb",
    "jni/arm64-v8a/libblur_faces.so": "69fe7cfaf3cb341a09354ac66550ca5b607731d05852a61f90b895725e738203",
    "model/head_det.param": "92c7a174f29da140da77c6a1a192691bc8c693509ee0fb9c0e75a98a9f8fa915",
}

MODEL_BIN_URL = "https://github.com/gemeguardian/BlurFaces/releases/download/v1.0.0/head_det.bin"
MODEL_BIN_SHA256 = "df250b1cc91b56e90af9e62b7a1decba35e17a30d4129df49aea161c21444fea"
MODEL_BIN_SIZE = 6047932
