# Generated by build.py; ./build.sh refreshes these fixed runtime expectations.
ASSET_HASHES = {
    "dex/core.dex": "455afa2fdda3e7cba8475ef9a61abc8fac4b728baa3b3f4101348abfc8f81f6f",
    "jni/arm64-v8a/libblur_faces.so": "40fae2e476115ca68993997bd0984bd1cb06fdfd2faa72fadba0715fc1edeeeb",
    "model/head_det.bin": "7aaafe2c2921aad54363a3a859fa9f67c0f2b1589c59e1e8c38208d5a41499d0",
    "model/head_det.param": "294ca3b93ff08f75ef68186472adb0c72b933c03500ca4ac59cabf429a840e2d",
}
